// SPDX-License-Identifier: no SPDX license 
/* THIS FILE IS GENERATED BY THE GEN_KINEIS_CREDENTIALS tool */
/**
******************************************************************************
* @file   kineis_data.c
* @author kineis
* @brief  provides encrypted data to be used by the WL code for credentials provisionning
******************************************************************************
* @attention
*
* <h2><center>&copy; Copyright (c) 2022 Kineis.
* All rights reserved.</center></h2>
*
* This software component is licensed by Kineis under Ultimate Liberty license
* , the "License"; You may not use this file except in compliance with
* the License. You may obtain a copy of the License at:
                             kineis.com 

******************************************************************************
*** Your credentials are : ID ADDR[0..3] = 4B484D40 and ID(dec) =239997  
*** For the following board :01 94 0A 00 15 E1 80 00 
******************************************************************************/ 
#include <stdint.h>

uint8_t encrypted_kineis_data[64]  = {
0x37, 0x26, 0xC5, 0xB1, 0xB0, 0xE4, 0x0C, 0xBC, 0x2E, 0x30, 0xDC, 0x53, 0x18, 0xCC, 0xD3, 0x4B, 
0xE8, 0x6D, 0xEE, 0x09, 0xC9, 0xB4, 0xBE, 0xE5, 0xBB, 0xAA, 0xF8, 0x15, 0x1F, 0x8E, 0xC1, 0xFB, 
0xED, 0x8C, 0x7E, 0xF5, 0x53, 0x5F, 0xF7, 0x0B, 0x3E, 0xC4, 0x7C, 0xCB, 0xF9, 0xE0, 0x72, 0x87, 
0x94, 0x50, 0xB3, 0x92, 0x2A, 0x19, 0x38, 0xBC, 0xA2, 0x88, 0x3D, 0xC0, 0x16, 0xEE, 0x4C, 0x2C 
};

 /*end kineis_data.c */


/************************ (C) COPYRIGHT KINEIS **********************/ 

 /*****END OF FILE****/
